/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSetupPasswordRouteImport } from './routes/auth/setup-password'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthPendingVerificationRouteImport } from './routes/auth/pending-verification'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedUnlocksIndexRouteImport } from './routes/_protected/unlocks/index'
import { Route as ProtectedRequestsIndexRouteImport } from './routes/_protected/requests/index'
import { Route as ProtectedIndividualsIndexRouteImport } from './routes/_protected/individuals/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedCompaniesIndexRouteImport } from './routes/_protected/companies/index'
import { Route as ProtectedRequestsRequestIdRouteImport } from './routes/_protected/requests/$requestId'
import { Route as ProtectedCompaniesCompanyIdRouteImport } from './routes/_protected/companies/$companyId'
import { Route as ProtectedRequestsPaymentFailedRequestIdRouteImport } from './routes/_protected/requests/payment-failed.$requestId'
import { Route as ProtectedRequestsNewIndividualRouteImport } from './routes/_protected/requests/new.individual'
import { Route as ProtectedRequestsNewCompanyRouteImport } from './routes/_protected/requests/new.company'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupPasswordRoute = AuthSetupPasswordRouteImport.update({
  id: '/auth/setup-password',
  path: '/auth/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingVerificationRoute = AuthPendingVerificationRouteImport.update({
  id: '/auth/pending-verification',
  path: '/auth/pending-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUnlocksIndexRoute = ProtectedUnlocksIndexRouteImport.update({
  id: '/unlocks/',
  path: '/unlocks/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRequestsIndexRoute = ProtectedRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedIndividualsIndexRoute =
  ProtectedIndividualsIndexRouteImport.update({
    id: '/individuals/',
    path: '/individuals/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCompaniesIndexRoute = ProtectedCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRequestsRequestIdRoute =
  ProtectedRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCompaniesCompanyIdRoute =
  ProtectedCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedRequestsPaymentFailedRequestIdRoute =
  ProtectedRequestsPaymentFailedRequestIdRouteImport.update({
    id: '/requests/payment-failed/$requestId',
    path: '/requests/payment-failed/$requestId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedRequestsNewIndividualRoute =
  ProtectedRequestsNewIndividualRouteImport.update({
    id: '/requests/new/individual',
    path: '/requests/new/individual',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedRequestsNewCompanyRoute =
  ProtectedRequestsNewCompanyRouteImport.update({
    id: '/requests/new/company',
    path: '/requests/new/company',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/solutions': typeof SolutionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/requests/$requestId': typeof ProtectedRequestsRequestIdRoute
  '/companies/': typeof ProtectedCompaniesIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/individuals/': typeof ProtectedIndividualsIndexRoute
  '/requests/': typeof ProtectedRequestsIndexRoute
  '/unlocks/': typeof ProtectedUnlocksIndexRoute
  '/requests/new/company': typeof ProtectedRequestsNewCompanyRoute
  '/requests/new/individual': typeof ProtectedRequestsNewIndividualRoute
  '/requests/payment-failed/$requestId': typeof ProtectedRequestsPaymentFailedRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/solutions': typeof SolutionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/requests/$requestId': typeof ProtectedRequestsRequestIdRoute
  '/companies': typeof ProtectedCompaniesIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/individuals': typeof ProtectedIndividualsIndexRoute
  '/requests': typeof ProtectedRequestsIndexRoute
  '/unlocks': typeof ProtectedUnlocksIndexRoute
  '/requests/new/company': typeof ProtectedRequestsNewCompanyRoute
  '/requests/new/individual': typeof ProtectedRequestsNewIndividualRoute
  '/requests/payment-failed/$requestId': typeof ProtectedRequestsPaymentFailedRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/solutions': typeof SolutionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_protected/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/_protected/requests/$requestId': typeof ProtectedRequestsRequestIdRoute
  '/_protected/companies/': typeof ProtectedCompaniesIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/individuals/': typeof ProtectedIndividualsIndexRoute
  '/_protected/requests/': typeof ProtectedRequestsIndexRoute
  '/_protected/unlocks/': typeof ProtectedUnlocksIndexRoute
  '/_protected/requests/new/company': typeof ProtectedRequestsNewCompanyRoute
  '/_protected/requests/new/individual': typeof ProtectedRequestsNewIndividualRoute
  '/_protected/requests/payment-failed/$requestId': typeof ProtectedRequestsPaymentFailedRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/solutions'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/reset'
    | '/auth/setup-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/companies/$companyId'
    | '/requests/$requestId'
    | '/companies/'
    | '/dashboard/'
    | '/individuals/'
    | '/requests/'
    | '/unlocks/'
    | '/requests/new/company'
    | '/requests/new/individual'
    | '/requests/payment-failed/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/solutions'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/reset'
    | '/auth/setup-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/companies/$companyId'
    | '/requests/$requestId'
    | '/companies'
    | '/dashboard'
    | '/individuals'
    | '/requests'
    | '/unlocks'
    | '/requests/new/company'
    | '/requests/new/individual'
    | '/requests/payment-failed/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about-us'
    | '/solutions'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/reset'
    | '/auth/setup-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/_protected/companies/$companyId'
    | '/_protected/requests/$requestId'
    | '/_protected/companies/'
    | '/_protected/dashboard/'
    | '/_protected/individuals/'
    | '/_protected/requests/'
    | '/_protected/unlocks/'
    | '/_protected/requests/new/company'
    | '/_protected/requests/new/individual'
    | '/_protected/requests/payment-failed/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  SolutionsRoute: typeof SolutionsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPendingVerificationRoute: typeof AuthPendingVerificationRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSetupPasswordRoute: typeof AuthSetupPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup-password': {
      id: '/auth/setup-password'
      path: '/auth/setup-password'
      fullPath: '/auth/setup-password'
      preLoaderRoute: typeof AuthSetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pending-verification': {
      id: '/auth/pending-verification'
      path: '/auth/pending-verification'
      fullPath: '/auth/pending-verification'
      preLoaderRoute: typeof AuthPendingVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/unlocks/': {
      id: '/_protected/unlocks/'
      path: '/unlocks'
      fullPath: '/unlocks/'
      preLoaderRoute: typeof ProtectedUnlocksIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/requests/': {
      id: '/_protected/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof ProtectedRequestsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/individuals/': {
      id: '/_protected/individuals/'
      path: '/individuals'
      fullPath: '/individuals/'
      preLoaderRoute: typeof ProtectedIndividualsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/companies/': {
      id: '/_protected/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof ProtectedCompaniesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/requests/$requestId': {
      id: '/_protected/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof ProtectedRequestsRequestIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/companies/$companyId': {
      id: '/_protected/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof ProtectedCompaniesCompanyIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/requests/payment-failed/$requestId': {
      id: '/_protected/requests/payment-failed/$requestId'
      path: '/requests/payment-failed/$requestId'
      fullPath: '/requests/payment-failed/$requestId'
      preLoaderRoute: typeof ProtectedRequestsPaymentFailedRequestIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/requests/new/individual': {
      id: '/_protected/requests/new/individual'
      path: '/requests/new/individual'
      fullPath: '/requests/new/individual'
      preLoaderRoute: typeof ProtectedRequestsNewIndividualRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/requests/new/company': {
      id: '/_protected/requests/new/company'
      path: '/requests/new/company'
      fullPath: '/requests/new/company'
      preLoaderRoute: typeof ProtectedRequestsNewCompanyRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedCompaniesCompanyIdRoute: typeof ProtectedCompaniesCompanyIdRoute
  ProtectedRequestsRequestIdRoute: typeof ProtectedRequestsRequestIdRoute
  ProtectedCompaniesIndexRoute: typeof ProtectedCompaniesIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedIndividualsIndexRoute: typeof ProtectedIndividualsIndexRoute
  ProtectedRequestsIndexRoute: typeof ProtectedRequestsIndexRoute
  ProtectedUnlocksIndexRoute: typeof ProtectedUnlocksIndexRoute
  ProtectedRequestsNewCompanyRoute: typeof ProtectedRequestsNewCompanyRoute
  ProtectedRequestsNewIndividualRoute: typeof ProtectedRequestsNewIndividualRoute
  ProtectedRequestsPaymentFailedRequestIdRoute: typeof ProtectedRequestsPaymentFailedRequestIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCompaniesCompanyIdRoute: ProtectedCompaniesCompanyIdRoute,
  ProtectedRequestsRequestIdRoute: ProtectedRequestsRequestIdRoute,
  ProtectedCompaniesIndexRoute: ProtectedCompaniesIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedIndividualsIndexRoute: ProtectedIndividualsIndexRoute,
  ProtectedRequestsIndexRoute: ProtectedRequestsIndexRoute,
  ProtectedUnlocksIndexRoute: ProtectedUnlocksIndexRoute,
  ProtectedRequestsNewCompanyRoute: ProtectedRequestsNewCompanyRoute,
  ProtectedRequestsNewIndividualRoute: ProtectedRequestsNewIndividualRoute,
  ProtectedRequestsPaymentFailedRequestIdRoute:
    ProtectedRequestsPaymentFailedRequestIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  SolutionsRoute: SolutionsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPendingVerificationRoute: AuthPendingVerificationRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSetupPasswordRoute: AuthSetupPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
